FROM php:7.3.6-fpm-alpine3.9
RUN apk add bash mysql-client --no-cache openssl
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /usr/share/nginx
RUN rm -rf /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /usr/share/nginx
RUN composer install && \
    php artisan config:cache && \
    chmod -R 777 storage

RUN ln -s public html

EXPOSE 9000
ENTRYPOINT ["php-fpm"]
