version: '3'

services:

    app:
        build: .
        container_name: app
        volumes:
            - .:/var/www
        networks:
            - app-network
        #entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/app/entrypoint.sh
        depends_on:
            - db
            - redis
        #environment:
        #    - DB_HOST=127.0.0.1
        #    - DB_DATABASE=db
        #    - DB_USERNAME=root
        #    - DB_PASSWORD=root

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: db
        tty: true
        restart: always
        command: --innodb-use-native-aio=0
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
